# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 21:34
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seg_id', models.IntegerField(null=True)),
                ('attempts', models.IntegerField(verbose_name='Total Attempts at Segment')),
                ('geom', django.contrib.gis.db.models.fields.MultiPointField(srid=4326)),
            ],
        ),
    ]
